### ISSUE TITLE
npm commands in package.json do not work

### ISSUE THREAD

**Issue by rabrown1** [v-checha/node-typescript-mongodb#12]
npm run build
> node-distributor@2.0.3 build C:\Users\rich\Documents\VS Code\NodeDist
> webpack

Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: 87ccad28c868acfdf4fd
Version: webpack 4.30.0
Time: 40ms
Built at: 04/15/2019 11:19:51 AM

ERROR in Entry module not found: Error: Can't resolve './src/index.ts' in 'C:\Users\rich\Documents\VS Code\NodeDist'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! node-distributor@2.0.3 build: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the node-distributor@2.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rich\AppData\Roaming\npm-cache\_logs\2019-04-15T15_19_51_831Z-debug.log
[2019-04-15T15_19_51_831Z-debug.log](https://github.com/ChechaValerii/node-typescript-mongodb/files/3080843/2019-04-15T15_19_51_831Z-debug.log)

**Comment by VitaliyDanchul** [comment]
@rabrown1 , thank you for your feedback and took the time to write this issue

**Comment by rabrown1** [comment]
That works. Thank you very much, especially your rapid fix.
