### ISSUE TITLE
Error in src\config\oauth\index.ts

### ISSUE THREAD

**Issue by yurisnel** [v-checha/node-typescript-mongodb#22]
Hello!
Excellent work, thank you very much! 

I had a problem 
src\config\oauth\index.ts line 185 
if (result.ok) have error, never exist. 
which causes it to always return false and from where it is called it is returned that the code generated an exception does not exist 
<img width="386" alt="e1" src="https://user-images.githubusercontent.com/15690958/145648558-0833aa83-c809-4202-b575-52baff77897c.png">

I solved like this 
return result.deletedCount;
<img width="395" alt="s1" src="https://user-images.githubusercontent.com/15690958/145648689-4af80c52-deb3-42d1-b4ab-e5aa7ee11d01.png">

Greetings,
Yurisnel.

**Comment by v-checha** [comment]
> Hello! Excellent work, thank you very much!
> 
> I had a problem src\config\oauth\index.ts line 185 if (result.ok) have error, never exist. which causes it to always return false and from where it is called it is returned that the code generated an exception does not exist <img alt="e1" width="386" src="https://user-images.githubusercontent.com/15690958/145648558-0833aa83-c809-4202-b575-52baff77897c.png">
> 
> I solved like this return result.deletedCount; <img alt="s1" width="395" src="https://user-images.githubusercontent.com/15690958/145648689-4af80c52-deb3-42d1-b4ab-e5aa7ee11d01.png">
> 
> Greetings, Yurisnel.

Hello, thank you, we will fix it in next release.

**Comment by v-checha** [comment]
fixed in v2.5.2

**Comment by ChechaValerii** [comment]
fixed in v2.5.2
